<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.test.learning.TimeOutTest" tests="2" time="5.030" ignored="1" failures="0" timestamp="26 一月 2021 14:28:03 GMT" skipped="0" hostname="WIN10-20180414V" errors="1">
  <testcase name="timeOutFailed" time="3.015" classname="com.test.learning.TimeOutTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.test.learning.TimeOutTest.timeOutFailed() didn&#039;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.test.learning.TimeOutTest.timeOutFailed() didn't finish within the time-out 3000
]]>
    </error>
  </testcase> <!-- timeOutFailed -->
  <testcase name="timeOutSuccess" time="2.015" classname="com.test.learning.TimeOutTest"/>
  <testcase name="ignoreTestTwo" classname="com.test.learning.IgnoreTest">
    <skipped/>
  </testcase> <!-- ignoreTestTwo -->
</testsuite> <!-- com.test.learning.TimeOutTest -->
